version: '3.8'

services:
  backend:
    build:
      context: ./back-end
      dockerfile: Dockerfile
    image: flask-api-cors
    ports:
      - "5252"

  frontend:
    build:
      context: ./front-end
      dockerfile: Dockerfile
    image: softy-frontend-dynamic
    ports:
      - "9000"
    depends_on:
      - backend
  
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    image: proxy-nginx
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
